services:
  mongodb:
    image: sc:3.0
    container_name: crawler
    ports:
      - 3000:3000
    restart: always 
    networks:
      - crawler
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"

networks:
  crawler:
    driver: bridge
