services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27018:27017
    volumes:
      - ./database:/data/db
    command: mongod --noauth
    networks:
      - backend

  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./logs:/var/log/nginx"
      - "./html:/usr/share/nginx/html"
      - "./home:/home"
    networks:
      - backend

networks:
  backend:
    driver: bridge
